// <auto-generated />
using System;
using EcdsApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EcdsApp.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220109090709_LookupBoundary")]
    partial class LookupBoundary
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("EcdsApp.Models.AdminBoundaryDistrict", b =>
                {
                    b.Property<string>("DistrictGeoCode")
                        .HasColumnType("varchar(4)")
                        .HasColumnName("dist_geo_code");

                    b.Property<string>("DistrictName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("dist_name");

                    b.Property<string>("DistrictNameBangla")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("dist_name_bangla");

                    b.Property<string>("DivisionGeoCode")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("div_geo_code");

                    b.Property<string>("OldGeoCode")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("old_geo_code");

                    b.Property<int?>("SortingOrder")
                        .HasColumnType("int")
                        .HasColumnName("sorting_order");

                    b.HasKey("DistrictGeoCode");

                    b.HasIndex("DivisionGeoCode");

                    b.ToTable("lkp_admin_boundary_districts");
                });

            modelBuilder.Entity("EcdsApp.Models.AdminBoundaryDivision", b =>
                {
                    b.Property<string>("DivisionGeoCode")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("div_geo_code");

                    b.Property<string>("DivisionName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("div_name");

                    b.Property<string>("DivisionNameBangla")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("div_name_bangla");

                    b.Property<string>("OldGeoCode")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("old_geo_code");

                    b.Property<int?>("SortingOrder")
                        .HasColumnType("int")
                        .HasColumnName("sorting_order");

                    b.HasKey("DivisionGeoCode");

                    b.ToTable("lkp_admin_boundary_divisions");
                });

            modelBuilder.Entity("EcdsApp.Models.AdminBoundaryUpazila", b =>
                {
                    b.Property<string>("UpazilaGeoCode")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("upz_geo_code");

                    b.Property<string>("CityGeoCode")
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("city_geo_code");

                    b.Property<string>("CityName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("city_name");

                    b.Property<string>("DistrictGeoCode")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("dist_geo_code");

                    b.Property<string>("OldGeoCode")
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("old_geo_code");

                    b.Property<int?>("SortingOrder")
                        .HasColumnType("int")
                        .HasColumnName("sorting_order");

                    b.Property<string>("UpazilaName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("upz_name");

                    b.Property<string>("UpazilaNameBangla")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("upz_name_bangla");

                    b.HasKey("UpazilaGeoCode");

                    b.HasIndex("DistrictGeoCode");

                    b.ToTable("lkp_admin_boundary_upazilas");
                });

            modelBuilder.Entity("EcdsApp.Models.TabularModels.TableColumnInfo", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("DbColumnName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("db_column_name");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("display_name");

                    b.Property<string>("ModelPropertyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("model_property_name");

                    b.Property<int>("TableId")
                        .HasColumnType("int")
                        .HasColumnName("table_id");

                    b.HasKey("Id");

                    b.HasIndex("TableId");

                    b.ToTable("tbl_table_column_info");
                });

            modelBuilder.Entity("EcdsApp.Models.TabularModels.TableInfo", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("display_name");

                    b.Property<int>("SubThemeId")
                        .HasColumnType("int")
                        .HasColumnName("sub_theme_id");

                    b.Property<string>("TableModelName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("table_model_name");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("table_name");

                    b.HasKey("Id");

                    b.HasIndex("SubThemeId");

                    b.ToTable("tbl_table_info");
                });

            modelBuilder.Entity("EcdsApp.Models.ThemeModels.LayerLegendColor", b =>
                {
                    b.Property<int>("LayerLegendColorId")
                        .HasColumnType("int")
                        .HasColumnName("layer_legend_color_id");

                    b.Property<int>("LayerId")
                        .HasColumnType("int")
                        .HasColumnName("layer_id");

                    b.Property<string>("LayerLegendColorCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("layer_legend_color_code");

                    b.Property<string>("LayerLegendDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("layer_legend_display_name");

                    b.Property<string>("LayerMainAttribureValue")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("layer_main_attribure_value");

                    b.HasKey("LayerLegendColorId");

                    b.HasIndex("LayerId");

                    b.ToTable("tbl_layer_legend_colors");
                });

            modelBuilder.Entity("EcdsApp.Models.ThemeModels.MetaDataDetail", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Abstract")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("abstract");

                    b.Property<string>("AdditionalInfoSourceForDataset")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("additional_info_source_for_dataset");

                    b.Property<string>("Completeness")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("completeness");

                    b.Property<string>("DatasetLanguage")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("dataset_language");

                    b.Property<string>("General")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("general");

                    b.Property<string>("HistoryOfTheDataset")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("history_of_the_dataset");

                    b.Property<int>("LayerId")
                        .HasColumnType("int")
                        .HasColumnName("layer_id");

                    b.Property<string>("ProcessDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("process_description");

                    b.Property<string>("PurposeOfProduction")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("purpose_of_production");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("quality");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("title");

                    b.Property<string>("TypeOfDataset")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("type_of_dataset");

                    b.HasKey("Id");

                    b.HasIndex("LayerId");

                    b.ToTable("tbl_metadata_details");
                });

            modelBuilder.Entity("EcdsApp.Models.ThemeModels.SubTheme", b =>
                {
                    b.Property<int>("SubThemeId")
                        .HasColumnType("int")
                        .HasColumnName("sub_theme_id");

                    b.Property<string>("SubThemeName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("sub_theme_name");

                    b.Property<string>("SubThemePath")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("sub_theme_path");

                    b.Property<int>("ThemeId")
                        .HasColumnType("int")
                        .HasColumnName("theme_id");

                    b.HasKey("SubThemeId");

                    b.HasIndex("ThemeId");

                    b.ToTable("lkp_sub_themes");
                });

            modelBuilder.Entity("EcdsApp.Models.ThemeModels.Theme", b =>
                {
                    b.Property<int>("ThemeId")
                        .HasColumnType("int")
                        .HasColumnName("theme_id");

                    b.Property<string>("ThemeName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("theme_name");

                    b.Property<string>("ThemePath")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("theme_path");

                    b.HasKey("ThemeId");

                    b.ToTable("lkp_themes");
                });

            modelBuilder.Entity("EcdsApp.Models.ThemeModels.ThemeLayerDetail", b =>
                {
                    b.Property<int>("LayerId")
                        .HasColumnType("int")
                        .HasColumnName("layer_id");

                    b.Property<string>("FileLatName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("file_lat_name");

                    b.Property<string>("FileLongName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("file_long_name");

                    b.Property<string>("FillColorCode")
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)")
                        .HasColumnName("fill_color_code");

                    b.Property<decimal>("FillOpacity")
                        .HasColumnType("decimal(1, 1)")
                        .HasColumnName("fill_opacity");

                    b.Property<string>("FirstAttributeCode")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("first_attribute_code");

                    b.Property<string>("FirstAttributeDisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("first_attribute_display_name");

                    b.Property<string>("FirstAttributeName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("first_attribute_name");

                    b.Property<bool>("IsLegendColor")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_legend_color");

                    b.Property<string>("LayerFileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("layer_file_name");

                    b.Property<string>("LayerName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("layer_name");

                    b.Property<string>("LayerPath")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("layer_path");

                    b.Property<int>("LayerTypeId")
                        .HasColumnType("int")
                        .HasColumnName("layer_type_id");

                    b.Property<string>("LegendColorFieldName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("legend_color_field_name");

                    b.Property<string>("LineColorCode")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)")
                        .HasColumnName("line_color_code");

                    b.Property<decimal>("LineWeight")
                        .HasColumnType("decimal(1, 1)")
                        .HasColumnName("line_weight");

                    b.Property<string>("MainAttributeCode")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("main_attribute_code");

                    b.Property<string>("MainAttributeDisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("main_attribute_display_name");

                    b.Property<string>("MainAttributeName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("main_attribute_name");

                    b.Property<decimal>("Opacity")
                        .HasColumnType("decimal(1, 1)")
                        .HasColumnName("opacity");

                    b.Property<string>("SecondAttributeCode")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("second_attribute_code");

                    b.Property<string>("SecondAttributeDisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("second_attribute_display_name");

                    b.Property<string>("SecondAttributeName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("second_attribute_name");

                    b.Property<int>("SubThemeId")
                        .HasColumnType("int")
                        .HasColumnName("sub_theme_id");

                    b.Property<string>("ThirdAttributeCode")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("third_attribute_code");

                    b.Property<string>("ThirdAttributeDisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("third_attribute_display_name");

                    b.Property<string>("ThirdAttributeName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("third_attribute_name");

                    b.HasKey("LayerId");

                    b.HasIndex("LayerTypeId");

                    b.HasIndex("SubThemeId");

                    b.ToTable("tbl_theme_layer_details");
                });

            modelBuilder.Entity("EcdsApp.Models.ThemeModels.ThemeLayerType", b =>
                {
                    b.Property<int>("LayerTypeId")
                        .HasColumnType("int")
                        .HasColumnName("layer_type_id");

                    b.Property<string>("LayerTypeName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("Layer_type_name");

                    b.HasKey("LayerTypeId");

                    b.ToTable("lkp_theme_layer_types");
                });

            modelBuilder.Entity("EcdsApp.Models.UpazilaWiseInfoModels.ExposureCategory", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category_name");

                    b.HasKey("Id");

                    b.ToTable("lkp_exposure_category");
                });

            modelBuilder.Entity("EcdsApp.Models.UpazilaWiseInfoModels.UpazilaWiseExposureData", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int?>("DroughtValue")
                        .HasColumnType("int")
                        .HasColumnName("drought_value");

                    b.Property<int?>("EarthquakeValue")
                        .HasColumnType("int")
                        .HasColumnName("earthquake_value");

                    b.Property<int?>("FloodValue")
                        .HasColumnType("int")
                        .HasColumnName("flood_value");

                    b.Property<int?>("LandSlideValue")
                        .HasColumnType("int")
                        .HasColumnName("land_slide_value");

                    b.Property<int?>("StormSurgeValue")
                        .HasColumnType("int")
                        .HasColumnName("storm_surge_value");

                    b.Property<int?>("TsunamiValue")
                        .HasColumnType("int")
                        .HasColumnName("tsunami_value");

                    b.Property<string>("UpazilaGeoCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("upz_geo_code");

                    b.HasKey("Id");

                    b.HasIndex("DroughtValue");

                    b.HasIndex("EarthquakeValue");

                    b.HasIndex("FloodValue");

                    b.HasIndex("LandSlideValue");

                    b.HasIndex("StormSurgeValue");

                    b.HasIndex("TsunamiValue");

                    b.HasIndex("UpazilaGeoCode");

                    b.ToTable("tbl_upazila_wise_exposure_data");
                });

            modelBuilder.Entity("EcdsApp.Models.UserManage.UserRegistration", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)")
                        .HasColumnName("user_id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime?>("DateOfCreation")
                        .HasColumnType("datetime")
                        .HasColumnName("date_of_creation");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_verified");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("last_modified_date");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("two_factor_enabled");

                    b.Property<int?>("UserActivationStatusId")
                        .HasColumnType("int")
                        .HasColumnName("user_activation_status_id");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("user_name");

                    b.Property<string>("VerificationCode")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("verification_code");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)")
                        .HasColumnName("role_id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("user_role_lists");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_yype");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(767)")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("user_role_claims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(767)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_claims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(767)")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(767)")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(767)")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("user_logins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(767)")
                        .HasColumnName("user_id");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(767)")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(767)")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(767)")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(767)")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("user_tokens");
                });

            modelBuilder.Entity("EcdsApp.Models.AdminBoundaryDistrict", b =>
                {
                    b.HasOne("EcdsApp.Models.AdminBoundaryDivision", "Division")
                        .WithMany()
                        .HasForeignKey("DivisionGeoCode");

                    b.Navigation("Division");
                });

            modelBuilder.Entity("EcdsApp.Models.AdminBoundaryUpazila", b =>
                {
                    b.HasOne("EcdsApp.Models.AdminBoundaryDistrict", "District")
                        .WithMany()
                        .HasForeignKey("DistrictGeoCode");

                    b.Navigation("District");
                });

            modelBuilder.Entity("EcdsApp.Models.TabularModels.TableColumnInfo", b =>
                {
                    b.HasOne("EcdsApp.Models.TabularModels.TableInfo", "TableInfo")
                        .WithMany()
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TableInfo");
                });

            modelBuilder.Entity("EcdsApp.Models.TabularModels.TableInfo", b =>
                {
                    b.HasOne("EcdsApp.Models.ThemeModels.SubTheme", "SubThemes")
                        .WithMany()
                        .HasForeignKey("SubThemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubThemes");
                });

            modelBuilder.Entity("EcdsApp.Models.ThemeModels.LayerLegendColor", b =>
                {
                    b.HasOne("EcdsApp.Models.ThemeModels.ThemeLayerDetail", "ThemeLayerDetails")
                        .WithMany()
                        .HasForeignKey("LayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ThemeLayerDetails");
                });

            modelBuilder.Entity("EcdsApp.Models.ThemeModels.MetaDataDetail", b =>
                {
                    b.HasOne("EcdsApp.Models.ThemeModels.ThemeLayerDetail", "ThemeLayerDetails")
                        .WithMany()
                        .HasForeignKey("LayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ThemeLayerDetails");
                });

            modelBuilder.Entity("EcdsApp.Models.ThemeModels.SubTheme", b =>
                {
                    b.HasOne("EcdsApp.Models.ThemeModels.Theme", "Themes")
                        .WithMany()
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Themes");
                });

            modelBuilder.Entity("EcdsApp.Models.ThemeModels.ThemeLayerDetail", b =>
                {
                    b.HasOne("EcdsApp.Models.ThemeModels.ThemeLayerType", "ThemeLayerTypes")
                        .WithMany()
                        .HasForeignKey("LayerTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcdsApp.Models.ThemeModels.SubTheme", "SubThemes")
                        .WithMany()
                        .HasForeignKey("SubThemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubThemes");

                    b.Navigation("ThemeLayerTypes");
                });

            modelBuilder.Entity("EcdsApp.Models.UpazilaWiseInfoModels.UpazilaWiseExposureData", b =>
                {
                    b.HasOne("EcdsApp.Models.UpazilaWiseInfoModels.ExposureCategory", "DroughtExposure")
                        .WithMany()
                        .HasForeignKey("DroughtValue");

                    b.HasOne("EcdsApp.Models.UpazilaWiseInfoModels.ExposureCategory", "EarthquakeExposure")
                        .WithMany()
                        .HasForeignKey("EarthquakeValue");

                    b.HasOne("EcdsApp.Models.UpazilaWiseInfoModels.ExposureCategory", "FloodExposure")
                        .WithMany()
                        .HasForeignKey("FloodValue");

                    b.HasOne("EcdsApp.Models.UpazilaWiseInfoModels.ExposureCategory", "LandSlideExposure")
                        .WithMany()
                        .HasForeignKey("LandSlideValue");

                    b.HasOne("EcdsApp.Models.UpazilaWiseInfoModels.ExposureCategory", "StormSurgeExposure")
                        .WithMany()
                        .HasForeignKey("StormSurgeValue");

                    b.HasOne("EcdsApp.Models.UpazilaWiseInfoModels.ExposureCategory", "TsunamiExposure")
                        .WithMany()
                        .HasForeignKey("TsunamiValue");

                    b.HasOne("EcdsApp.Models.AdminBoundaryUpazila", "Upazila")
                        .WithMany()
                        .HasForeignKey("UpazilaGeoCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DroughtExposure");

                    b.Navigation("EarthquakeExposure");

                    b.Navigation("FloodExposure");

                    b.Navigation("LandSlideExposure");

                    b.Navigation("StormSurgeExposure");

                    b.Navigation("TsunamiExposure");

                    b.Navigation("Upazila");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("EcdsApp.Models.UserManage.UserRegistration", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("EcdsApp.Models.UserManage.UserRegistration", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcdsApp.Models.UserManage.UserRegistration", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("EcdsApp.Models.UserManage.UserRegistration", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
